/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package me.petrov.algorithmik.roulette;

/**
 *
 * @author Jonkler
 */
public class RouletteJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RouletteJFrame.class.getName());
    private int lastGuess;
    private int numberToGuess;
    private int tries;
    private static final int DEFAULT_TRIES = 5;
    
    /**
     * Creates new form RouletteJFrame
     */
    public RouletteJFrame() {
        initComponents();
        this.startNewGame();
    }
    
    private void startNewGame() {
        this.lastGuess = -1;
        
        // generate new number
        this.numberToGuess = (int) (Math.random() * 100 + 1);
        
        // reset UI
        guessInput.setText("");
        checkGuessButton.setEnabled(true);
        guessResultLabel.setText("N/A");
        
        // reset countdown to default
        this.setTries(DEFAULT_TRIES);
        System.out.println(numberToGuess);
    }
    
    private void setTries(int tries) {
        this.tries = tries;
        triesLeftLabel.setText(String.valueOf(tries));  // update counter
        // auto end on tries exhausted
        if (tries <= 0) {
            guessResultLabel.setText("You lost ;(");
            endGame();
        }
    }
    
    private void endGame() {
        checkGuessButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        guessInput = new javax.swing.JTextField();
        guessLabel = new javax.swing.JLabel();
        checkGuessButton = new javax.swing.JButton();
        guessResultHint = new javax.swing.JLabel();
        guessResultLabel = new javax.swing.JLabel();
        triesLeftHint = new javax.swing.JLabel();
        triesLeftLabel = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COURT JESTER - WIN REAL ELECTRONS");
        setAlwaysOnTop(true);
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Guess the number game");
        titleLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        guessInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessInputActionPerformed(evt);
            }
        });

        guessLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        guessLabel.setText("Your guess");

        checkGuessButton.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        checkGuessButton.setText("Check!");
        checkGuessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkGuessButtonActionPerformed(evt);
            }
        });

        guessResultHint.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        guessResultHint.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        guessResultHint.setText("Result: ");

        guessResultLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        guessResultLabel.setText("N/A");

        triesLeftHint.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        triesLeftHint.setText("Tries left:");

        triesLeftLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        triesLeftLabel.setText("N/A");

        resetButton.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        resetButton.setText("Reset!");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guessResultHint, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(guessResultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(checkGuessButton, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guessLabel)
                        .addGap(18, 18, 18)
                        .addComponent(guessInput, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(105, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(triesLeftHint)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(triesLeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guessInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guessLabel))
                .addGap(18, 18, 18)
                .addComponent(checkGuessButton)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guessResultHint)
                    .addComponent(guessResultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(triesLeftHint)
                        .addComponent(triesLeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(resetButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void guessInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_guessInputActionPerformed

    private void checkGuessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkGuessButtonActionPerformed
        String rawGuess = guessInput.getText();
        int guess;
        
        try {
            guess = Integer.parseInt(rawGuess);
        } catch (NumberFormatException exception) {
            //guessResultLabel.setText("Input an integer from 1 to 100!!!");
            guessResultLabel.setText("Invalid input!");
            return;
        }
        
        if (guess < 0 || guess > 100) {
            guessResultLabel.setText("0 < x < 100");
            return;
        }
        
        if (guess == lastGuess){
            return;
        }
        
        if (guess == numberToGuess) {
            guessResultLabel.setText("YOU'RE WINNER!!");
            this.endGame();
            return;
        } else if (numberToGuess > guess) {
            guessResultLabel.setText("Target is greater!");
        } else if (numberToGuess < guess) {
            guessResultLabel.setText("Target is less!");
        }
        
        this.lastGuess = guess;
        this.setTries(this.tries - 1);
    }//GEN-LAST:event_checkGuessButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        this.startNewGame();
    }//GEN-LAST:event_resetButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RouletteJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkGuessButton;
    private javax.swing.JTextField guessInput;
    private javax.swing.JLabel guessLabel;
    private javax.swing.JLabel guessResultHint;
    private javax.swing.JLabel guessResultLabel;
    private javax.swing.JButton resetButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel triesLeftHint;
    private javax.swing.JLabel triesLeftLabel;
    // End of variables declaration//GEN-END:variables
}
