/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package me.petrov.algorithmik.arrayler;

/**
 *
 * @author Samuil Petrov
 */
public class HighScoreJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HighScoreJFrame.class.getName());
    private final int[] scores = new int[10];

    /**
     * Creates new form HighScoreJFrame
     */
    public HighScoreJFrame() {
        initComponents();
        fillScoresArray();
        updateScoresArrayDisplay();
    }
    
    private void fillScoresArray() {
        for (int i = 0; i < scores.length; i++) {
            scores[i] = 100;
        }
    }
    
    private void updateScoresArrayDisplay() {
        resultLabel.setText(scoresArrayToString());
    }
    
    private String scoresArrayToString() {
        StringBuilder resultBuilder = new StringBuilder("<html>");
        
        for (int i = 0; i < scores.length; i++) {
            resultBuilder.append("&nbsp;")
                    .append(String.format("%02d", i + 1))
                    .append(". ")
                    .append(scores[i])
                    .append("<br>");
        }
        
        return resultBuilder.append("</html>").toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        valueInputPanel = new javax.swing.JPanel();
        valueInputHint = new javax.swing.JLabel();
        valueInput = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("High Score List");
        setAlwaysOnTop(true);
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("High Score List");
        titleLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        resultLabel.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        resultLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        valueInputHint.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        valueInputHint.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valueInputHint.setText("Value: ");

        valueInput.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        valueInput.setPreferredSize(new java.awt.Dimension(70, 30));

        javax.swing.GroupLayout valueInputPanelLayout = new javax.swing.GroupLayout(valueInputPanel);
        valueInputPanel.setLayout(valueInputPanelLayout);
        valueInputPanelLayout.setHorizontalGroup(
            valueInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valueInputPanelLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(valueInputHint, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueInput, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        valueInputPanelLayout.setVerticalGroup(
            valueInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(valueInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(valueInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueInputHint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        addButton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        addButton.setText("Add");
        addButton.setFocusable(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addButton)
                        .addGap(153, 153, 153)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resultLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(valueInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String rawValue = valueInput.getText();
        int value;

        try {
            value = Integer.parseInt(rawValue);
        } catch (NumberFormatException exception) {
            resultLabel.setText("Invalid input!");
            return;
        }
        
        if (value < 0) {
            resultLabel.setText("Input may not be negative!");
            return;
        }
        
        for (int i = 0; i < scores.length; i++) {
            // search for the place for the new value
            if (scores[i] <= value) {
                continue;
            }
            // move all the elements after the place to make room
            for (int j = scores.length - 1; j > i; j--) {
                scores[j] = scores[j - 1];
            }
            // set the value on the found place
            scores[i] = value;
            break;
        }
        
        updateScoresArrayDisplay();
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HighScoreJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField valueInput;
    private javax.swing.JLabel valueInputHint;
    private javax.swing.JPanel valueInputPanel;
    // End of variables declaration//GEN-END:variables
}
