/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package me.petrov.algorithmik.arrayler;

/**
 *
 * @author Jonkler
 */
public class RangerJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RangerJFrame.class.getName());
    private int[] numbers = new int[50];
    
    /**
     * Creates new form RangerJFrame
     */
    public RangerJFrame() {
        initComponents();
        fillNumbersArray();
        updateNumbersArrayDisplay();
    }
    
    private void fillNumbersArray() {
        for (int i = 0; i < numbers.length; i++) {
            numbers[i] = (int) (Math.random()*100);
        }
    }
    
    private void updateNumbersArrayDisplay() {
        resultLabel.setText(numbersArrayToString());
    }
    
    private String numbersArrayToString() {
        StringBuilder resultBuilder = new StringBuilder("<html>");
        for (int i = 0; i < numbers.length; i++) {
            resultBuilder
                    .append(String.format("%02d", i))
                    .append(". ")
                    .append(String.format("%03d", numbers[i]));
            
            if (i == 0 || (i + 1) % 5 != 0) {
                resultBuilder.append("&nbsp;&nbsp;&nbsp;");
            } else {
                resultBuilder.append("<br>");
            }
        }
        return resultBuilder.append("</html>").toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        resultScrollPane = new javax.swing.JScrollPane();
        resultLabel = new javax.swing.JLabel();
        valueInputPanel = new javax.swing.JPanel();
        valueInputHint = new javax.swing.JLabel();
        valueInput = new javax.swing.JTextField();
        indexInputPanel = new javax.swing.JPanel();
        indexInputHint = new javax.swing.JLabel();
        indexInput = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ranger");
        setAlwaysOnTop(true);
        setResizable(false);

        titleLabel.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Ranger");
        titleLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        resultLabel.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        resultLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        resultLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        resultScrollPane.setViewportView(resultLabel);

        valueInputHint.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        valueInputHint.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        valueInputHint.setText("Value: ");

        valueInput.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        valueInput.setPreferredSize(new java.awt.Dimension(70, 30));

        javax.swing.GroupLayout valueInputPanelLayout = new javax.swing.GroupLayout(valueInputPanel);
        valueInputPanel.setLayout(valueInputPanelLayout);
        valueInputPanelLayout.setHorizontalGroup(
            valueInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 170, Short.MAX_VALUE)
            .addGroup(valueInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(valueInputPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(valueInputHint, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(valueInput, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        valueInputPanelLayout.setVerticalGroup(
            valueInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
            .addGroup(valueInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(valueInputPanelLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addGroup(valueInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(valueInputHint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(valueInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        indexInputHint.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        indexInputHint.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        indexInputHint.setText("Index: ");

        indexInput.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        indexInput.setPreferredSize(new java.awt.Dimension(70, 30));

        javax.swing.GroupLayout indexInputPanelLayout = new javax.swing.GroupLayout(indexInputPanel);
        indexInputPanel.setLayout(indexInputPanelLayout);
        indexInputPanelLayout.setHorizontalGroup(
            indexInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 158, Short.MAX_VALUE)
            .addGroup(indexInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(indexInputPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(indexInputHint, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(indexInput, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        indexInputPanelLayout.setVerticalGroup(
            indexInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(indexInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(indexInputPanelLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addGroup(indexInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(indexInputHint, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(indexInput, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        addButton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        addButton.setText("Add");
        addButton.setFocusable(false);
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(valueInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(indexInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(addButton)
                .addGap(158, 158, 158))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultScrollPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(indexInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(valueInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addButton)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String rawValue = valueInput.getText();
        String rawIndex = indexInput.getText();
        int value, index;
        
        try {
            value = Integer.parseInt(rawValue);
            index = Integer.parseInt(rawIndex);
        } catch (NumberFormatException exception) {
            resultLabel.setText("Invalid input!");
            return;
        }
        
        if (value < 0 || value > 100) {
            resultLabel.setText("0 <= value <= 100");
            return;
        }
        
        if (index < 0 || index > numbers.length) {
            resultLabel.setText("0 <= index <= max index + 1");
            return;
        }
        
        int[] newNumbers = new int[numbers.length + 1];
        
        for (int i = 0; i < index; i++) {
            newNumbers[i] = numbers[i];
        }
        
        newNumbers[index] = value;
        
        for (int i = index; i < numbers.length; i++) {
            newNumbers[i + 1] = numbers[i];
        }
        
        this.numbers = newNumbers;
        updateNumbersArrayDisplay();
    }//GEN-LAST:event_addButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RangerJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField indexInput;
    private javax.swing.JLabel indexInputHint;
    private javax.swing.JPanel indexInputPanel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JScrollPane resultScrollPane;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField valueInput;
    private javax.swing.JLabel valueInputHint;
    private javax.swing.JPanel valueInputPanel;
    // End of variables declaration//GEN-END:variables
}
