/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package me.petrov.algorithmik.helloworld;

import javax.swing.SwingWorker;
import java.awt.Cursor;


/**
 *
 * @author Samuil Petrov
 * @author Marcos Esteban Gorena
 */
public class HelloWorldJFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HelloWorldJFrame.class.getName());

    /**
     * Creates new form MainJFrame
     */
    public HelloWorldJFrame() {
        initComponents();
        // Fake progress bar
        new SwingWorker() {
            @Override
            protected Object doInBackground() throws InterruptedException {
                int progress = clickMeProgressBar.getValue();
                for (int i = 0; i < 10; i++) {
                    Thread.sleep(1000);
                    progress += 10;
                    clickMeProgressBar.setValue(progress);
                }
                clickMeProgressBar.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
                clickMeProgressBar.setToolTipText("Surprise ready!");
                clickMeButton.setEnabled(true);

                return null;
            }
        }.execute();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        secretLabel = new javax.swing.JLabel();
        clickMeButton = new javax.swing.JButton();
        clickMeProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Super Secret Window");
        setAlwaysOnTop(true);
        setResizable(false);

        secretLabel.setFont(new java.awt.Font("Jokerman", 3, 24)); // NOI18N
        secretLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        secretLabel.setText("Nothing to see here...");
        secretLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        clickMeButton.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        clickMeButton.setText("Click me!");
        clickMeButton.setToolTipText("Click for a surprise");
        clickMeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clickMeButton.setEnabled(false);
        clickMeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clickMeButtonActionPerformed(evt);
            }
        });

        clickMeProgressBar.setToolTipText("Preparing your surprise...");
        clickMeProgressBar.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clickMeProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clickMeButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(secretLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(secretLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(clickMeProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(clickMeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void clickMeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clickMeButtonActionPerformed
        secretLabel.setText("Hello, world!");
        clickMeButton.setEnabled(false);
        clickMeButton.setToolTipText("Surprise collected!");
    }//GEN-LAST:event_clickMeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HelloWorldJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JButton clickMeButton;
    private static javax.swing.JProgressBar clickMeProgressBar;
    private static javax.swing.JLabel secretLabel;
    // End of variables declaration//GEN-END:variables
}
